INSERT INTO USER_DETAILS (ID, NAME, BIRTH_DATE) VALUES (10001, 'Michael', current_date())
INSERT INTO USER_DETAILS (ID, NAME, BIRTH_DATE) VALUES (10002, 'Dwight', current_date())
INSERT INTO USER_DETAILS (ID, NAME, BIRTH_DATE) VALUES (10003, 'Jim', current_date())